services:
  web:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    image: game_store:1.0.0
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "chmod +x /app/migrate.sh && chmod +x /app/collectstatic.sh && sh /app/migrate.sh && sh /app/collectstatic.sh && /app/entrypoint.sh"
    volumes:
      - staticfiles:/app/staticfiles/
  postgres_db:
    image: postgres
    restart: always
    command: -p 5432
    env_file:
      - .env
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  staticfiles:
  postgres_data:
