services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: game_store:1.0.0
    environment:
      - PORT=8000
    env_file:
      - web/.env
    ports:
      - "8000:8000"
    command: sh -c "/app/entrypoint.sh"
