# Generated by Django 4.1.1 on 2022-09-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=120)),
                ('genre', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('developer', models.TextField(max_length=100)),
                ('publisher', models.TextField(max_length=100)),
                ('rating_for', models.TextField(blank=True, choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], max_length=20, null=True)),
            ],
        ),
    ]
