# Generated by Django 4.1.1 on 2022-09-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating_for',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
