# Generated by Django 4.1.1 on 2022-09-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_developer_alter_game_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
